netdata:
  image:
    tag: edge

  restarter:
    enabled: true

  parent:
    claiming:
      enabled: true
      token: ""  # Will be set via Rancher GUI
      rooms: ""  # Will be set via Rancher GUI

  child:
    claiming:
      enabled: true
      token: ""  # Will be set via Rancher GUI
      rooms: ""  # Will be set via Rancher GUI